######################################################################
#
# File name : CPU_tb_simulate.do
# Created on: Mon Apr 14 19:07:47 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.CPU_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {CPU_tb_wave.do}

view wave
view structure
view signals

do {CPU_tb.udo}

run 1000ns
