######################################################################
#
# File name : CPU_tb_wave.do
# Created on: Mon Apr 14 19:04:48 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
