######################################################################
#
# File name : CPU_tb_compile.do
# Created on: Mon Apr 14 19:07:45 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\Modelsim2020.4\\win64\\vlib modelsim_lib/work
E:\\Modelsim2020.4\\win64\\vlib modelsim_lib/msim

E:\\Modelsim2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim2020.4\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../../rtl/ALU.v" \
"../../../../../rtl/ALU_control.v" \
"../../../../../rtl/CPU.v" \
"../../../../../rtl/DM_module.v" \
"../../../../../rtl/ImmExtend.v" \
"../../../../../rtl/PC_module.v" \
"../../../../../rtl/PM_module.v" \
"../../../../../rtl/Register_file.v" \
"../../../../../rtl/control.v" \
"../../../../../tb/tb_CPU.v" \


# compile glbl module
E:\\Modelsim2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

